version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myburguer
      POSTGRES_PASSWORD: mb
      POSTGRES_DB: myburguer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  myburguer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://db:5432/myburguer"
      DATABASE_USER: "myburguer"
      DATABASE_PASSWORD: "mb"
      WIREMOCK_URL: "http://localhost:9090/mercadopago/pagamento"
      JWT_KEY: "lkjhaskljdajkdlsfjklsdgjklssdljkgff"
      LOG_LEVEL: "DEBUG"
  wiremock:
    platform: linux/amd64
    image: holomekc/wiremock-gui:3.5.7-alpine
    ports:
      - "9090:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

volumes:
  pgdata:

networks:
  myburger:
    driver: bridge
