version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  myburguer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      PAYMENT_INTEGRATION_URL: ${PAYMENT_INTEGRATION_URL}
      PAYMENT_INTEGRATION_AUTH_TOKEN: ${PAYMENT_INTEGRATION_AUTH_TOKEN}
      LOG_LEVEL: "DEBUG"
  wiremock:
    platform: linux/amd64
    image: holomekc/wiremock-gui:3.5.7-alpine
    ports:
      - "9090:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]

volumes:
  pgdata:

networks:
  myburger:
    driver: bridge
