version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: myburguer
      POSTGRES_PASSWORD: mb
      POSTGRES_DB: myburguer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: