apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgresql
    type: DirectoryOrCreate
