apiVersion: apps/v1
kind: Deployment
metadata:
  name: myburger
spec:
  selector:
    matchLabels:
      app: myburger
  replicas: 2
  template:
    metadata:
      labels:
        app: myburger
    spec:
      containers:
        - name: myburger
          image: fiapmyburguer/myburgercontrol-clean-arch:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1000Mi"
              cpu: "400m"
            requests:
                memory: "512Mi"
                cpu: "200m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myburger-config
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
