apiVersion: apps/v1
kind: Deployment
metadata:
  name: myburguer
spec:
  selector:
    matchLabels:
      app: myburguer
  replicas: 2
  template:
    metadata:
      labels:
        app: myburguer
    spec:
      containers:
        - name: myburguer
          image: fiapmyburguer/myburgercontrol-clean-arch:latest
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myburguer-config
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/liveness
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/readiness
            initialDelaySeconds: 360
            periodSeconds: 10
            failureThreshold: 5
