name: CI MyBurger

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'

    - name: Setup Gradle [MyBurger ≡]
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Run build [MyBurger ≡]
      run: ./gradlew clean build --no-daemon -x test

    - name: Run tests [MyBurger ≡]
      run: ./gradlew test --info --stacktrace

    - name: Generate JaCoCo Test Coverage Report [MyBurger ≡]
      run: ./gradlew jacocoTestReport

    - name: Get current date [MyBurger ≡]
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Check Test Coverage [MyBurger ≡]
      run: |
        echo "Test Coverage Report:"
        cat build/reports/jacoco/test/html/index.html

    - name: Upload JaCoCo Test Coverage Report to Artifacts [MyBurger ≡]
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: build/reports/jacoco/test/html/

    - name: Authentication Docker Hub [MyBurger ≡]
      uses: docker/login-action@v3.2.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}

    - name: Build the Docker image [MyBurger ≡]
      uses: docker/build-push-action@v6.0.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          fiapmyburguer/myburgercontrol-clean-arch:${{ steps.date.outputs.date }}
          fiapmyburguer/myburgercontrol-clean-arch:latest
