name: CD Pipeline with Terraform (DigitalOcean)

on:
  push:
    branches:
      - main
      - feature/start-deploy-actions
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set DigitalOcean Credentials
        run: echo "${{ secrets.DO_TOKEN_ACCESS }}" > ~/.digitalocean_token

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_FINGERPRINT }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
    
