name: CD [MyBurger ≡] (DigitalOcean)

on:
  push:
    branches:
      - main
      - feature/start-deploy-actions
jobs:
  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    env:
       IMAGE_NAME: fiapmyburguer/myburgercontrol-clean-arch:latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Autenticação com a DigitalOcean
      - name: Set up DigitalOcean [MyBurger ≡]
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN_ACCESS }}

      # Armazenar o ID do primeiro cluster na variável de ambiente
      - name: Get First Cluster ID [MyBurger ≡]
        run: |
          CLUSTER_ID=$(doctl kubernetes cluster list --format ID --no-header | head -n 1)
          echo "CLUSTER_ID=$CLUSTER_ID" >> $GITHUB_ENV

      - name: Create tfvars file
        run: |
          echo "digitalocean_token = \"${{ secrets.DO_TOKEN_ACCESS }}\"" >> terraform.tfvars
          echo "ssh_fingerprint = \"${{ secrets.DO_SSH_FINGERPRINT }}\"" >> terraform.tfvars

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: .github/workflows/  # Especificar o diretório correto

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: .github/workflows/

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: .github/workflows/

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false \
          -var "digitalocean_token=${{ secrets.DO_TOKEN_ACCESS }}" \
          -var "ssh_fingerprint=${{ secrets.DO_SSH_FINGERPRINT }}"
        working-directory: .github/workflows/  # Especificar o diretório correto
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN_ACCESS }}
          SSH_FINGERPRINT: ${{ secrets.DO_SSH_FINGERPRINT }}

      - name: Deploy to Droplet
        run: |
          DROPLET_IP=$(terraform output -raw droplet_ip)
          ssh root@${DROPLET_IP} <<EOF
            docker pull ${{ env.IMAGE_NAME }}
            docker stop myburger || true
            docker rm myburger || true
            docker run -d --name myburger -p 80:8080 ${{ env.IMAGE_NAME }}
          EOF

      # Autenticação com o cluster Kubernetes
      - name: Set up Kubernetes [MyBurger ≡]
        run: |
          doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER_ID }}

      # Validar autenticação
      - name: Validate Auth [MyBurger ≡]
        run: |
          kubectl get nodes

      # Armazenar o Context do primeiro cluster na variável de ambiente
      - name: Get First Context [MyBurger ≡]
        run: |
          KUBE_CONTEXT=$(kubectl config get-contexts --no-headers | head -n 1 | awk '{print $2}')
          echo "KUBE_CONTEXT=$KUBE_CONTEXT" >> $GITHUB_ENV

      # Configura o contexto
      - name: Config context [MyBurger ≡]
        run: |
          kubectl config use-context ${{ env.KUBE_CONTEXT }}

      # Aplicar os manifests do Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/app/myburger-configmap.yaml
          kubectl apply -f k8s/app/myburger-secret.yaml
          kubectl apply -f k8s/app/myburger-deployment.yaml
          kubectl apply -f k8s/app/myburger-hpa.yaml
          kubectl apply -f k8s/app/myburger-svc.yaml

      # Armazenar o nome do deployment na variável de ambiente
      - name: Get Deployment Name [MyBurger ≡]
        run: |
          kubectl get deployments
          DEPLOYMENT_NAME=$(kubectl get deployments --namespace=default -o jsonpath='{.items[0].metadata.name}')
          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV

      # Atualizar a imagem do deployment
      - name: Update Image [MyBurger ≡]
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} myburger=${{ env.IMAGE_NAME }}

      # Verificar o status dos pods
      - name: Check pod status [MyBurger ≡]
        run: |
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}

      # Ver logs dos pods atualizados
      - name: View Logs [MyBurger ≡]
        run: |
          kubectl logs -l app=${{ env.DEPLOYMENT_NAME }} --tail=100
