name: CD Pipeline with Terraform (DigitalOcean)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set DigitalOcean Credentials
        run: echo "${{ secrets.DO_TOKEN_ACCESS }}" > ~/.digitalocean_token

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
